version: '3.3'

services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
    networks:
      mongonet:
        aliases:
          - "mongonet"
networks:
  mongonet:
    driver: bridge
volumes:
  mongodb:
  mongodb_config: